### PR TITLE
Add custom logging functionality documentation

### PR DESCRIPTION
**Pull request by IamCathal**
Added documentation for the custom logging format functionality that I worked on as described  in https://github.com/astaxie/beego/pull/4216 and https://github.com/astaxie/beego/pull/4188

Let me know if anything needs changing and I'll be happy to refactor this addition

### CODE REVIEW

**Comment by IamCathal** [comment]
This might also be needed for [the pkg/logs README.md](https://github.com/astaxie/beego/tree/ftr/log_format/pkg/logs) so let me know if it needs to be there aswell

**Review by flycash — APPROVED** [review]
I just notice that you write the docs. Please @me or  I may ignore it.

**Comment by flycash** [comment]
It since that I don't have the merge authorization. sad

**Comment by IamCathal** [comment]
I guess I'll wait just in case someone who can merge this sees it. I'l try to remember to @ you in the future thanks :)

**Pull request merged**
