### PR TITLE
uz-UZ added 

### PR DESCRIPTION
**Pull request by faxriddin**

### CODE REVIEW

**Comment by astaxie** [comment]
@faxriddin it looks it's still use the english version. you still working on it now?

**Comment by faxriddin** [comment]
Yes, I just started it.

**Comment by astaxie** [comment]
@faxriddin awesome, when that done please inform me to merger it.

**Comment by faxriddin** [comment]
@astaxie  Ok. Thanks!

**Comment by mmirolim** [comment]
@faxriddin Great Job! if you need help, you know where to find me :)

**Comment by faxriddin** [comment]
Yes I know. @mmirolim thanks!

**Comment by astaxie** [comment]
@faxriddin still in process?

**Comment by faxriddin** [comment]
Yes, I do not have time.

On Wed, Dec 30, 2015 at 4:33 PM, astaxie <notifications@github.com> wrote:

> @faxriddin <https://github.com/faxriddin> still in process?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/beego/beedoc/pull/265#issuecomment-167983757>.
>



-- 

С уважением,
Фахриддин Балтаев

**Comment by astaxie** [comment]
:smiley: go for it when you are free

**Comment by faxriddin** [comment]
Ok!  👌

On Wed, Dec 30, 2015 at 6:11 PM, astaxie <notifications@github.com> wrote:

> [image: :smiley:] go for it when you are free
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/beego/beedoc/pull/265#issuecomment-167993459>.
>



-- 

С уважением,
Фахриддин Балтаев

**Comment by astaxie** [comment]
@faxriddin are you still working on the translation?

**Comment by astaxie** [comment]
I will close this PR as @faxriddin looks not working on this now

**Pull request closed without merging**
